version: 1.0.{build}
build:
  verbosity: minimal
deploy:
- provider: GitHub
  auth_token:
    secure: ba91tZnwPFaEUkA7MC5GHZQlJ8WAXs9fgwBNHzfRfyondI9kQY7QV/mLkD3CzpGIni5ICDHuwNM9YcXBqhB9hDivIvyGLvk/Sfhb/JPb2+8=
